load("@rules_proto//proto:defs.bzl", "proto_library")

licenses(["notice"])  # Apache 2

proto_library(
    name = "protos",
    visibility = ["//visibility:public"],
    deps = [
        "//tools/testdata/protoxform/envoy/v2:protos",
    ],
)
